#!/usr/bin/env bash
#
# Manage the 'manage_my_process' daemon

PROGRAM='manage_my_process'
RELPATH="${0%/*}/${PROGRAM}"
PIDFILE='/var/run/my_process.pid'
declare -A MESSAGES=(
  ['start']='started'
  ['stop']='stopped'
  ['restart']='restarted'
) 

start() {
  exec -- "${RELPATH}" &
  echo "$!"
} > "${PIDFILE}"

stop() {
  rm -f -- "${PIDFILE}"
  kill -- "$(< /dev/stdin)"
} < "${PIDFILE}"

restart() {
  stop
  start
}

if (( $# == 1 )) && [[ -v "MESSAGES[$1]" ]]
then
  "$1" 2>/dev/null && printf '%s %s\n' "${PROGRAM}" "${MESSAGES[$1]}"
else
  printf 'Usage: %s {start|stop|restart}\n' "${PROGRAM}"
  exit 1
fi
