#!/usr/bin/env bash
#
# Manage the 'manage_my_process' daemon

PIDFILE='/var/run/my_process.pid'
RELPATH="${0%/*}/manage_my_process"

declare -A message=( )

manage_my_process::start() {
  exec -- "${RELPATH}" &
  echo "$!" > "${PIDFILE}"
} && message['start']='started'

manage_my_process::stop() {
  kill -- "$(< "${PIDFILE}")"
  rm -f -- "${PIDFILE}"
} && message['stop']='stopped'

manage_my_process::restart() {
  manage_my_process::stop
  manage_my_process::start
} && message['restart']='restarted'

if (( $# == 1 )) && [[ -v "message[$1]" ]]
then
  manage_my_process::"$1"
  echo 'manage_my_process' "${message[$1]}"
else
  echo 'Usage: manage_my_process {start|stop|restart}'
  exit 1
fi
