#!/usr/bin/env bash
#
# Manage the 'manage_my_process' daemon

RELPATH="${BASH_SOURCE[0]%/*}/manage_my_process"
PIDFILE="${XDG_RUNTIME_DIR}/my_process.pid"

declare -A message

manage_my_process::start() {
  message['start']='manage_my_process started'
  exec -- "${RELPATH}" &
  echo "$!"
} > "${PIDFILE}"

manage_my_process::stop() {
  message['stop']='manage_my_process stopped'
  rm -f -- "${PIDFILE}"
  kill -- "$(< /dev/stdin)"
} < "${PIDFILE}"

manage_my_process::restart() {
  message['restart']='manage_my_process restarted'
  manage_my_process::stop
  manage_my_process::start
}

if (( $# == 1 )) && [[ $1 == @(start|stop|restart) ]]
then
  "manage_my_process::$1" && echo "${message[$1]}"
else
  echo 'Usage: manage_my_process {start|stop|restart}'
  exit 1
fi
