#!/usr/bin/env bash
#
# Group clients listed in Apache access log by IP and HTTP status code

awk '{ print $1,$9 }' "${1-apache-access.log}" |
    sort -n -s -k 2 |
    sort -n -s -t '.' -k 1,1 -k 2,2 -k 3,3 -k 4,4 |
    uniq -c |
    sort -b -n -r -k 1,1
