#!/usr/bin/env bash
#
# Configure resolution of localhost to 127.0.0.2 and facebook.com to 8.8.8.8

HOSTS=/etc/hosts

if (( ${UID:-$(id -u)} ))
then
  echo 'Must be run as root'
  exit 1
fi

if ! temp="$(mktemp)"
then
  echo 'Unable to create temporary file'
  exit 1
fi

{ printf '%s\t%s\n' 127.0.0.2 localhost
  printf '%s\t%s\n' 8.8.8.8 facebook.com
} > "${temp}"

cat -- "${HOSTS}" >> "${temp}"
cat -- "${temp}" >| "${HOSTS}"
