#!/usr/bin/env bash
# Run NGINX as nginx listening to all active IPs on port 8080
sed -i 's/\<listen *\( [^[:digit:]]*\)80 /listen\18080 /g' /etc/nginx/sites-enabled/default
chomd 0644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/sites-available/default
pkill -x apache2
sudo -u nginx service nginx restart
